/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter' at '5/3/14 5:33 PM' with Gradle 1.11
 *
 * @author peter, @date 5/3/14 5:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
