import com.kpelykh.docker.client.DockerClient;
import com.kpelykh.docker.client.model.Info;
import static org.junit.Assert.assertTrue;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'peter' at '5/3/14 5:33 PM' with Gradle 1.11
 *
 * @author peter, @date 5/3/14 5:33 PM
 */
public class Lib raryTest {
    @Test public void testSomeLibraryMethod() throws Exception{
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());


			DockerClient dockerClient = new DockerClient("http://localhost:4243");
			Info info = dockerClient.info();
			System.out.print(info);
    }
}
